# Generated by Django 3.1.3 on 2020-11-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201123_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='document',
            field=models.CharField(default='this document is blank', max_length=10000),
        ),
    ]
