# Generated by Django 3.1.3 on 2020-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201123_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='document',
            field=models.TextField(default='this document is blank', max_length=10000),
        ),
    ]
